/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ujian_sindiana_2440087031;


import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author somatech-devops
 */
public class form_pasien extends javax.swing.JFrame {
    
    private DefaultTableModel DftTblModel_pasien;
    private String SQL; 
    private String tgl;
    
    public void TampilData() {
        DftTblModel_pasien = new DefaultTableModel();
        DftTblModel_pasien.addColumn("No.");
        DftTblModel_pasien.addColumn("Nama Pasien");
        DftTblModel_pasien.addColumn("NIK");
        DftTblModel_pasien.addColumn("Tanggal Lahir");
        DftTblModel_pasien.addColumn("Alamat");
        DftTblModel_pasien.addColumn("Jenis Kelamin");
        DftTblModel_pasien.addColumn("No. Handphone");
        tblPasien.setModel(DftTblModel_pasien);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from pasien";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_pasien.addRow(new Object[]{
                    res.getString("no"),
                    res.getString("nama"),
                    res.getString("nik"),
                    res.getString("tgl_lahir"),
                    res.getString("alamat"),
                    res.getString("jenis_kelamin"),
                    res.getString("no_hp")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Creates new form form_pasien
     */
    public form_pasien() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNik = new javax.swing.JLabel();
        lblTglLahir = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblJK = new javax.swing.JLabel();
        lblNoHp = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNik = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();
        jDateTglLahir = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        cmbJK = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA PASIEN RS AMEENAH");

        lblNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNo.setText("No.");

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNama.setText("Nama Pasien");

        lblNik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNik.setText("NIK");

        lblTglLahir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTglLahir.setText("Tanggal Lahir");

        lblAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlamat.setText("Alamat");

        lblJK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblJK.setText("Jenis Kelamin");

        lblNoHp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNoHp.setText("No. Handphone");

        jDateTglLahir.setDateFormatString("dd MMM yyyy");
        jDateTglLahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateTglLahirPropertyChange(evt);
            }
        });

        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPasien);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        cmbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNoHp)
                            .addComponent(lblNo)
                            .addComponent(lblNama)
                            .addComponent(lblNik)
                            .addComponent(lblTglLahir)
                            .addComponent(lblAlamat)
                            .addComponent(lblJK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateTglLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(txtNik, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnSimpan)
                        .addGap(33, 33, 33)
                        .addComponent(btnUpdate)
                        .addGap(37, 37, 37)
                        .addComponent(btnHapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKeluar)
                    .addComponent(jLabel1))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNik)
                    .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateTglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTglLahir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlamat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJK)
                    .addComponent(cmbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoHp)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );

        lblNo.getAccessibleContext().setAccessibleName("lblNo");
        lblNama.getAccessibleContext().setAccessibleName("lblNama");
        lblNik.getAccessibleContext().setAccessibleName("lblNik");
        lblTglLahir.getAccessibleContext().setAccessibleName("lblTglLahir");
        lblAlamat.getAccessibleContext().setAccessibleName("lblAlamat");
        lblJK.getAccessibleContext().setAccessibleName("lblJK");
        lblNoHp.getAccessibleContext().setAccessibleName("lblNoHp");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String no = "",
                nama = "",
                nik = "",
                tgl_lahir = "",
                alamat = "",
                jenis_kelamin = "",
                no_hp = "";
        try {
            no = txtNo.getText();
            nama = txtNama.getText();
            nik = txtNik.getText();
            tgl_lahir = jDateTglLahir.getDateFormatString();
            alamat = txtAlamat.getText();
            jenis_kelamin = (String) cmbJK.getSelectedItem();
            no_hp = txtNoHp.getText();
            Connection conn = koneksi.getConnection();
            Statement stmt = conn.createStatement();
            String sql = "insert into pasien value ('"+no
                    +"','"+nama
                    +"','"+nik
                    +"','"+tanggal_lahir
                    +"','"+alamat
                    +"','"+jenis_kelamin
                    +"','"+no_hp+"')";
            stmt.execute(sql);
            TampilData();
            hapus();
        } catch (SQLException ex) {
            Logger.getLogger(form_pasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private String tanggal_lahir;
    public void tanggal(){
        if(jDateTglLahir.getDate() !=null) {
            String pattern = "dd MMMM yyyy";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            tanggal_lahir = String.valueOf(format.format(jDateTglLahir.getDate()));
        }
    }
    
    public void lahir() throws SQLException{
        try {
            Connection conn = koneksi.getConnection();
            Statement stmt = conn.createStatement();
            String sql = "select * from pasien where nik='" + txtNik.getText()+"'";
            java.sql.ResultSet r = stmt.executeQuery(sql);
            while (r.next()) {
                jDateTglLahir.setDate(r.getDate("tgl_lahir"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(form_pasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    public void hapus(){
        txtNo.setText("");
        txtNama.setText("");
        txtNik.setText("");
        
        txtAlamat.setText("");
        cmbJK.setSelectedItem("Laki-Laki");
        txtNoHp.setText("");
    }
    private void jDateTglLahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateTglLahirPropertyChange
        tanggal();
    }//GEN-LAST:event_jDateTglLahirPropertyChange

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        if (evt.getClickCount() == 1) {
            try {
                txtNo.setText(String.valueOf(tblPasien.getValueAt(tblPasien.getSelectedRow(),0)));
                txtNama.setText(String.valueOf(tblPasien.getValueAt(tblPasien.getSelectedRow(),1)));
                txtNik.setText(String.valueOf(tblPasien.getValueAt(tblPasien.getSelectedRow(),2)));
                lahir();
                txtAlamat.setText(String.valueOf(tblPasien.getValueAt(tblPasien.getSelectedRow(),4)));
                cmbJK.setSelectedItem(String.valueOf(tblPasien.getValueAt(tblPasien.getSelectedRow(),5)));
                txtNoHp.setText(String.valueOf(tblPasien.getValueAt(tblPasien.getSelectedRow(),6)));
            } catch (SQLException ex) {
                Logger.getLogger(form_pasien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblPasienMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            Connection conn = koneksi.getConnection();
            Statement stmt = conn.createStatement();
            String Sql = "update pasien set no='"+txtNo.getText()
                    +"',nama= '"+txtNama.getText()
                    +"',tgl_lahir= '"+tanggal_lahir
                    +"',alamat= '"+txtAlamat.getText()
                    +"',jenis_kelamin= '"+cmbJK.getSelectedItem()
                    +"',no_hp= '"+txtNoHp.getText()
                    +"'where nik= '"+txtNik.getText()+"'";
            stmt.execute(Sql);
            TampilData();
            hapus();
            
        } catch (SQLException ex) {
            Logger.getLogger(form_pasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            Connection conn = koneksi.getConnection();
            Statement stmt = conn.createStatement();
            String sql = "delete from pasien where nik='"+txtNik.getText()+"'";
            stmt.execute(sql);
            TampilData();
            hapus();
        } catch (SQLException ex) {
            Logger.getLogger(form_pasien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbJK;
    private com.toedter.calendar.JDateChooser jDateTglLahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblJK;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNoHp;
    private javax.swing.JLabel lblTglLahir;
    private javax.swing.JTable tblPasien;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables
}
